# fly.toml app configuration file generated for bold-sun-4741 on 2023-09-26T14:56:10-04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "bold-sun-4741"
primary_region = "ewr"

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
